data_platform:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: data-platform-portfolio
      dataset: dbt_dev
      location: US
      keyfile: /Users/gokulchandmallampati/.gcp/data-platform-key.json
      threads: 4
      timeout_seconds: 300
      priority: interactive

    prod:
      type: bigquery
      method: service-account
      project: data-platform-portfolio
      dataset: dbt_prod
      location: US
      keyfile: "{{ env_var('GOOGLE_APPLICATION_CREDENTIALS') }}"
      threads: 8
      timeout_seconds: 300
      priority: batch